### ISSUE TITLE
Problem with opening large .raw file (6 GB)

### ISSUE THREAD

**Issue by Minhusyd** [jungmannlab/picasso#129]
* Picasso version: Not sure (just downloaded 3 month ago)
* Python version: 3.8.2
* Operating System: Linux on Artemis

### Description

**I have a .raw file that is about 6 GB, when I tried to open it, I got this error:**

_Traceback (most recent call last):
  File "/usr/local/python/3.8.2/lib/python3.8/runpy.py", line 193, in _run_modu$
    return _run_code(code, main_globals, None,
  File "/usr/local/python/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/picasso-0.3.1-py3.8$
    main()
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/picasso-0.3.1-py3.8$
    _localize(args)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/picasso-0.3.1-py3.8$
    movie, info = load_movie(path)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/picasso-0.3.1-py3.8$
    return load_raw(path, prompt_info=prompt_info)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/picasso-0.3.1-py3.8$
    movie = _np.memmap(path, dtype, "r", shape=shape)
  File "/usr/local/python/3.8.2/lib/python3.8/site-packages/numpy/core/memmap.p$
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size_

**Then I switched to a different computer with python 2.7.1, window 7. I got this error:**

OSError: [WinError 8] Not enough storage is available to process this command

<img width="1440" alt="Screen Shot 2020-09-01 at 11 34 16 am" src="https://user-images.githubusercontent.com/70553511/91784911-62a47680-ec47-11ea-9f4f-29223c377468.png">

**Comment by straussmaximilian** [comment]
Hi,
In principle, this file size should work w/o problems.
Do you have enough free memory/ disk space?
Python 2.7 is unfortunately, not supported.
