### ISSUE TITLE
Issue opening "Picasso Average" result in "Picasso Render"

### ISSUE THREAD

**Issue by gwisna** [jungmannlab/picasso#142]
* Picasso version: 0.3.1
* Python version: 3.7.9
* Operating System: Windows 10 Home

### Description

Hi Max,

I am still having issue with opening the result from "Picasso Average" to "Picasso Render". I averaged 20 picks with "Picasso Average" and save the averaging result. I tried to open it in "Picasso Render" but I got several errors below. This cause me that I cannot use "unfold/refold groups" submenu. 

### What I Did
![image](https://user-images.githubusercontent.com/70862585/96970491-a342a280-14c8-11eb-8932-ea8b2704dba4.png)

```
(picasso378) C:\Users\wisna\Documents\picasso>python -m picasso render
100%|████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 21021.57it/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  5.64it/s]
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 7028, in excepthook
    errorbox.exec_()
AttributeError: 'StandardButton' object has no attribute 'exec_'

Original exception was:
Traceback (most recent call last):
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 6829, in open_file_dialog
    self.view.add(path)
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 2528, in add
    self.fit_in_view(autoscale=True)
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 3128, in fit_in_view
    self.update_scene(viewport=viewport, autoscale=autoscale)
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 5791, in update_scene
    points_only=points_only,
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 3072, in draw_scene
    autoscale=autoscale, use_cache=use_cache
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 4721, in render_scene
    kwargs, autoscale=autoscale, use_cache=use_cache, cache=cache
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 4904, in render_single_channel
    kwargs, autoscale=autoscale, locs=locs, use_cache=use_cache
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 4821, in render_multi_channel
    self.window.dataset_dialog.colorselection[i].currentText()
IndexError: list index out of range
```

Here is the list of packages installed on Anaconda3 env
# packages in environment at C:\Users\wisna\anaconda3\envs\picasso378:
#
# Name                    Version                   Build  Channel
asteval                   0.9.19                   pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2020.10.14                    0
certifi                   2020.6.20                py37_0
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
freetype                  2.10.4               hd328e21_0
future                    0.18.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.10.7               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
intel-openmp              2020.2                      254
joblib                    0.17.0                   pypi_0    pypi
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
kiwisolver                1.2.0                    pypi_0    pypi
libcxx                    7.0.0             h1ad3211_1002    conda-forge
libffi                    3.2.1             ha925a31_1007
libpng                    1.6.37               h2a8f88b_0
llvm-meta                 7.0.0                         0    conda-forge
llvmlite                  0.34.0                   pypi_0    pypi
lmfit                     1.0.1                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
matplotlib                3.3.2                    pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py37hb782905_0
msys2-conda-epoch         20160418                      1
numba                     0.51.2                   pypi_0    pypi
numpy                     1.19.2                   pypi_0    pypi
numpy-base                1.19.1           py37ha3acd2a_0
openssl                   1.1.1h               he774522_0
perfplot                  0.6.2                    pypi_0    pypi
picasso                   0.3.1                    pypi_0    pypi
pillow                    8.0.0                    pypi_0    pypi
pip                       20.2.4                   py37_0
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.1                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2020.1                     py_0
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.3                    pypi_0    pypi
setuptools                50.3.0           py37h9490d1a_1
sip                       4.19.24          py37ha925a31_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
termtables                0.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               he774522_0
tqdm                      4.50.2                   pypi_0    pypi
uncertainties             2.4.4                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zlib                      1.2.11               h62dcd97_4

**Comment by gwisna** [comment]
After discussing with Max, dragging and dropping file to the render window solves the issue. Open submenu seems to have bug.
![image](https://user-images.githubusercontent.com/70862585/97091224-2b22cc80-15ef-11eb-9089-4288bb194c6d.png)

(picasso378) C:\Users\wisna\Documents\picasso>python -m picasso render
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
100%|██████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<?, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00,  8.91it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 10.47it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 25.62it/s]
