### ISSUE TITLE
Issue on Mask Submenu

### ISSUE THREAD

**Issue by gwisna** [jungmannlab/picasso#143]
* Picasso version: 0.3.1
* Python version: 3.7.9
* Operating System:Windows 10 Home

### Description

I am trying to mask my render result using "Mask" submenu. But, I obtained some errors when trying to open the mask submenu.

### What I Did
![image](https://user-images.githubusercontent.com/70862585/96970418-85753d80-14c8-11eb-819f-33428fccfd7d.png)

```
(picasso378) C:\Users\wisna\Documents\picasso>python -m picasso render
[Errno 2] No such file or directory: 'D:/DNA-PAINT/20201016_Bima_Bayou_PEG10kg4C_2p5nM_2/Cropped_Bima_Bayou_PEG10kg4C_2p5nM_2_TIRF_300ms_30percent_15Kframes_locs_201017_134951_drift.txt'
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 7028, in excepthook
    errorbox.exec_()
AttributeError: 'StandardButton' object has no attribute 'exec_'

Original exception was:
Traceback (most recent call last):
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 1606, in init_dialog
    self.update_plots()
  File "C:\Users\wisna\Documents\picasso\picasso\gui\render.py", line 1715, in update_plots
    self.yedges[-1],
  File "C:\Users\wisna\anaconda3\envs\picasso378\lib\site-packages\matplotlib\__init__.py", line 1438, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\wisna\anaconda3\envs\picasso378\lib\site-packages\matplotlib\axes\_axes.py", line 5521, in imshow
    resample=resample, **kwargs)
  File "C:\Users\wisna\anaconda3\envs\picasso378\lib\site-packages\matplotlib\image.py", line 909, in __init__
    **kwargs
  File "C:\Users\wisna\anaconda3\envs\picasso378\lib\site-packages\matplotlib\image.py", line 246, in __init__
    cbook._check_in_list(["upper", "lower"], origin=origin)
  File "C:\Users\wisna\anaconda3\envs\picasso378\lib\site-packages\matplotlib\cbook\__init__.py", line 2268, in _check_in_list
    .format(v, k, ', '.join(map(repr, values))))
ValueError: 'low' is not a valid value for origin; supported values are 'upper', 'lower'
```
Here are the packages installed on the Anaconda3 env
(picasso378) C:\Users\wisna\Documents\picasso>conda list
# packages in environment at C:\Users\wisna\anaconda3\envs\picasso378:
#
# Name                    Version                   Build  Channel
asteval                   0.9.19                   pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2020.10.14                    0
certifi                   2020.6.20                py37_0
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
freetype                  2.10.4               hd328e21_0
future                    0.18.2                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
hdf5                      1.10.7               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
intel-openmp              2020.2                      254
joblib                    0.17.0                   pypi_0    pypi
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
kiwisolver                1.2.0                    pypi_0    pypi
libcxx                    7.0.0             h1ad3211_1002    conda-forge
libffi                    3.2.1             ha925a31_1007
libpng                    1.6.37               h2a8f88b_0
llvm-meta                 7.0.0                         0    conda-forge
llvmlite                  0.34.0                   pypi_0    pypi
lmfit                     1.0.1                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
matplotlib                3.3.2                    pypi_0    pypi
mkl                       2020.2                      256
mkl-service               2.3.0            py37hb782905_0
msys2-conda-epoch         20160418                      1
numba                     0.51.2                   pypi_0    pypi
numpy                     1.19.2                   pypi_0    pypi
numpy-base                1.19.1           py37ha3acd2a_0
openssl                   1.1.1h               he774522_0
perfplot                  0.6.2                    pypi_0    pypi
picasso                   0.3.1                    pypi_0    pypi
pillow                    8.0.0                    pypi_0    pypi
pip                       20.2.4                   py37_0
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.1                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2020.1                     py_0
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.3                    pypi_0    pypi
setuptools                50.3.0           py37h9490d1a_1
sip                       4.19.24          py37ha925a31_0
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
termtables                0.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               he774522_0
tqdm                      4.50.2                   pypi_0    pypi
uncertainties             3.1.4                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zlib                      1.2.11               h62dcd97_4

**Comment by gwisna** [comment]
I switched back to matplotlib 3.0.0 and the mask seems to work
![image](https://user-images.githubusercontent.com/70862585/97091154-a89a0d00-15ee-11eb-8366-abbe6563e218.png)


(picasso378) C:\Users\wisna\Documents\picasso>pip install matplotlib==3.0.0
Collecting matplotlib==3.0.0
  Using cached matplotlib-3.0.0-cp37-cp37m-win_amd64.whl (8.9 MB)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\wisna\anaconda3\envs\picasso378\lib\site-packages (from matplotlib==3.0.0) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\wisna\anaconda3\envs\picasso378\lib\site-packages (from matplotlib==3.0.0) (2.4.7)
Requirement already satisfied: numpy>=1.10.0 in c:\users\wisna\anaconda3\envs\picasso378\lib\site-packages (from matplotlib==3.0.0) (1.19.2)
Requirement already satisfied: cycler>=0.10 in c:\users\wisna\anaconda3\envs\picasso378\lib\site-packages (from matplotlib==3.0.0) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\wisna\anaconda3\envs\picasso378\lib\site-packages (from matplotlib==3.0.0) (2.8.1)
Requirement already satisfied: six in c:\users\wisna\anaconda3\envs\picasso378\lib\site-packages (from cycler>=0.10->matplotlib==3.0.0) (1.15.0)
Installing collected packages: matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.3.2
    Uninstalling matplotlib-3.3.2:
      Successfully uninstalled matplotlib-3.3.2
Successfully installed matplotlib-3.0.0

(picasso378) C:\Users\wisna\Documents\picasso>python -m picasso render
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
[Errno 2] No such file or directory: 'D:/DNA-PAINT/20201016_Bima_Bayou_PEG10kg4C_2p5nM_2/Cropped_Bima_Bayou_PEG10kg4C_2p5nM_2_TIRF_300ms_30percent_15Kframes_locs_201017_134951_drift.txt'
