### ISSUE TITLE
clusterfilter function of picassomodule 

### ISSUE THREAD

**Issue by SoohyenJang** [jungmannlab/picasso#449]
* Picasso version: 0.5.6
* Python version: 3.8
* Operating System: windows

### Description

I wanted to use 'clusterfilter' using anaconda prompt. I checked that you changed the column name of 'mean_frame' to 'frame'. However, I guess I cannot use clusterfilter function with clustered and cluster_centers file. 
If I could use clusterfilter, it would be so cool!

### What I Did
open Anaconda prompt and use command below for clusterfilter.
 
picasso clusterfilter 'clustered.hdf5' 'cluster_centers.hdf5' frame min_value max_value
```
then, I got the message below

Traceback (most recent call last):
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\Scripts\picasso.exe\__main__.py", line 7, in <module>
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\lib\site-packages\picasso\__main__.py", line 1607, in main
    _clusterfilter(
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\lib\site-packages\picasso\__main__.py", line 306, in _clusterfilter
    clusters = io.load_clusters(clusterfile)
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\lib\site-packages\picasso\io.py", line 1244, in load_clusters
    clusters = cluster_file["clusters"][...]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_env\lib\site-packages\h5py\_hl\group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'clusters' doesn't exist)"
```

**Comment by rafalkowalewski1** [comment]
Hello,
Thanks for raising the issue. We will improve this point in the next picasso release. 

Bests,
Rafal
