### ISSUE TITLE
clusterfilter_DBSCANed file and centers file cannot be used

### ISSUE THREAD

**Issue by SoohyenJang** [jungmannlab/picasso#481]
* Picasso version: 0.6.11
* Python version: 3.10
* Operating System: window

### Description

Thanks for matching the column names of DBSCAN and cluster centers file. 
I wanted to use clusterfilter using anaconda module. I used command in a way how I did before. But, it seems the DBSCANed and centers file do not specify or named each of column as clusters. So, the filter cannot be run.

### What I Did

>picasso clusterfilter "DBSCANed.hdf5" "DBSCANed_centers.hdf5" frame 5000 15000

Traceback (most recent call last):
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\Scripts\picasso.exe\__main__.py", line 7, in <module>
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\lib\site-packages\picasso\__main__.py", line 1700, in main
    _clusterfilter(
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\lib\site-packages\picasso\__main__.py", line 308, in _clusterfilter
    clusters = io.load_clusters(clusterfile)
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\lib\site-packages\picasso\io.py", line 1252, in load_clusters
    clusters = cluster_file["clusters"][...]
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\pcoffice79\anaconda3\envs\picasso_0611\lib\site-packages\h5py\_hl\group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5o.pyx", line 241, in h5py.h5o.open
KeyError: "Unable to synchronously open object (object 'clusters' doesn't exist)"

**Comment by rafalkowalewski1** [comment]
Hello,

Thank you for pointing out the problem. I will fix it in the next update. For now, if you're willing to run Picasso in developer mode (see here: https://github.com/jungmannlab/picasso?tab=readme-ov-file#for-developers), you can modify the function load_clusters in picasso/io.py

```
def load_clusters(path, qt_parent=None):
    with _h5py.File(path, "r") as cluster_file:
        try:
            clusters = cluster_file["clusters"][...]
        except KeyError:
            clusters = cluster_file["locs"][...]
    clusters = _np.rec.array(
        clusters, dtype=clusters.dtype
    )  
    return clusters
```

Please let me know if you have further questions.

Bests,
Rafal
